AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 80
  IgnoredPatterns: ['(\A|\s)#']
